GET http://localhost:3000/inscritos

###

GET http://localhost:3000/inscritos/634df03b8fa873743927d52e


###
POST http://localhost:3000/inscritos
Content-Type: application/json

{
    "tipoDocumento": "Tarjeta de Identidad",
    "identificacion": "1000004444",
    "nombres": "Elizabeth",
    "apellidos": "Gaitan Eslava",
    "direccion": "Calle 167 # 34 - 23",
    "correo": "eli.gaitaneslava@correo.com",
    "telefonoFijo": "7777777",
    "celular": "6559999999",
    "linkComprobante": "http://icfes.edu.co/comprobates/1155",
    "codigoIcfes": "1155",
    "familiarEstudiando": false,
    "estrato": 5,
    "tipoColegio": "Privado"
}

###
DELETE http://localhost:3000/inscritos/634df16f8fa873743927d532


###
PATCH http://localhost:3000/inscritos/634df4a9b851926e5ed7289d
Content-Type: application/json

{
    "tipoDocumento": "Cédula de Ciudadanía"
}

